'build_app':
  script:
  - apt-get update && apt-get install -y python-pip
  - pip install -r requirements.txt
  - python manage.py db upgrade
  - python manage.py install
  - python manage.py test
  tags:
  except:
  - tags