"""Remove Unique from PhotoGalleryItem

Revision ID: 296aeda7d38
Revises: 48ff3ef1bd6
Create Date: 2015-07-18 13:51:47.040065

"""

# revision identifiers, used by Alembic.
revision = '296aeda7d38'
down_revision = '48ff3ef1bd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
