"""BlogPostStatus

Revision ID: 29a0ce65138
Revises: 453a135f16e
Create Date: 2015-06-21 10:07:28.752528

"""

# revision identifiers, used by Alembic.
revision = '29a0ce65138'
down_revision = '453a135f16e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogpoststatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogposts', sa.Column('blogpoststatus_id', sa.Integer(), nullable=True))
    # Alembic doesn't have a workaround for SQLites lack of support for ALTERs
    # op.create_foreign_key(None, 'blogposts', 'blogpoststatus', ['blogpoststatus_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Alembic doesn't have a workaround for SQLites lack of support for ALTERs
    # op.drop_constraint(None, 'blogposts', type_='foreignkey')
    op.drop_column('blogposts', 'blogpoststatus_id')
    op.drop_table('blogpoststatus')
    ### end Alembic commands ###
