"""AddSlugToBlogCategory

Revision ID: 453a135f16e
Revises: 5474f10957e
Create Date: 2015-02-12 23:45:02.974428

"""

# revision identifiers, used by Alembic.
revision = '453a135f16e'
down_revision = '5474f10957e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogcategories', sa.Column('slug', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_blogcategories_slug'), 'blogcategories', ['slug'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogcategories_slug'), table_name='blogcategories')
    op.drop_column('blogcategories', 'slug')
    ### end Alembic commands ###
