"""Adding Site Settings

Revision ID: 48ff3ef1bd6
Revises: 7f28d3d32
Create Date: 2015-06-30 10:37:57.988300

"""

# revision identifiers, used by Alembic.
revision = '48ff3ef1bd6'
down_revision = '7f28d3d32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitesettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitesettings')
    ### end Alembic commands ###
