"""adding site settings

Revision ID: 54e9d038ef1
Revises: 7f28d3d32
Create Date: 2015-06-25 08:04:35.268251

"""

# revision identifiers, used by Alembic.
revision = '54e9d038ef1'
down_revision = '7f28d3d32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
